export { default as Hero } from './Hero'
export { default as About } from './About'
export { default as Impact } from './Impact'
export { default as Programs } from './Programs'
export { default as CTA } from './CTA'
export { default as Problem } from './Problem'
export { default as Solution } from './Solution'
export { default as HowItWorks } from './HowItWorks'
